"""
prompts — Prompt 模板包

拆分为以下模块：
  search.py      — 搜索规划、相关性检查、深挖查询、自主发现
  extraction.py  — 原文摘录、FEMWC 评分、帖子过滤、需求聚类
  debate.py      — 导演/产品经理/杠精 system prompt + 注入模板
  report.py      — 产品提案、深挖报告、最终报告、直接报告
  competitor.py  — 竞品搜索规划 & 信息提取
  poc_eval.py    — POC 产品验证

所有常量在此统一导出，保持向后兼容（from prompts import XXX）。
"""

from prompts.search import (
    SEARCH_PLANNING_PROMPT,
    BATCH_RELEVANCE_PROMPT,
    QUICK_RELEVANCE_PROMPT,
    DEEP_MINING_QUERY_PROMPT,
    AUTO_DISCOVER_PROMPT,
    QUICK_SEARCH_QUERY_CLASSIFIER_PROMPT,
    QUICK_SEARCH_PLANNING_PROMPT,
    QUICK_SEARCH_MARKET_PLANNING_PROMPT,
    QUICK_SEARCH_MARKET_REPAIR_PROMPT,
    QUICK_SEARCH_SUMMARY_PROMPT,
    QUICK_SEARCH_SUMMARY_PROMPT_EN,
    QUICK_SEARCH_PROCESS_SUMMARY_PROMPT,
    QUICK_SEARCH_PROCESS_SUMMARY_PROMPT_EN,
    QUICK_SEARCH_TOPIC_PROMPT,
    QUICK_SEARCH_TRANSLATE_PROMPT,
)

from prompts.extraction import (
    QUOTE_EXTRACTION_PROMPT,
    FEMWC_SCORING_PROMPT,
    POST_FILTER_PROMPT,
    CLUSTERING_PROMPT,
    CLUSTERING_STEP1_PROMPT,
    CLUSTERING_STEP2_PROMPT,
)

from prompts.debate import (
    DIRECTOR_SYSTEM_PROMPT,
    DIRECTOR_INITIAL_PROMPT,
    DIRECTOR_EVALUATE_PROMPT,
    DIRECTOR_TOPICS_PROMPT,
    DIRECTOR_FREE_TOPICS_PROMPT,
    DIRECTOR_WRAP_PROMPT,
    DIRECTOR_VERDICT_PROMPT,
    PM_SYSTEM_PROMPT,
    PM_FIRST_TOPIC_PROMPT,
    PM_FREE_FIRST_TOPIC_PROMPT,
    PM_TOPIC_PROMPT,
    PM_COUNTER_PROMPT,
    CRITIC_SYSTEM_PROMPT,
    CRITIC_TOPIC_PROMPT,
    CRITIC_FREE_TOPIC_PROMPT,
    CRITIC_FOLLOWUP_PROMPT,
    CRITIC_FREE_FOLLOWUP_PROMPT,
    INVESTOR_SYSTEM_PROMPT,
    INVESTOR_BG_ANALYSIS_PROMPT,
    INVESTOR_FREE_BG_ANALYSIS_PROMPT,
    INVESTOR_FINAL_PROMPT,
    INVESTOR_FREE_FINAL_PROMPT,
    HUMAN_INJECT_PM,
    HUMAN_INJECT_CRITIC,
    ANALYST_SYSTEM_PROMPT,
    ANALYST_INITIAL_PROMPT,
    CRITIC_INITIAL_PROMPT,
    INJECT_TO_ANALYST,
    INJECT_TO_CRITIC,
)

from prompts.report import (
    PRODUCT_PROPOSAL_PROMPT,
    DEEP_DIVE_SYSTEM_PROMPT,
    DEEP_DIVE_SEARCH_PLAN_PROMPT,
    DEEP_DIVE_ANALYSIS_PROMPT,
    FINAL_REPORT_PROMPT,
    DIRECT_REPORT_PROMPT,
    DIRECT_REPORT_PROMPT_EN,
    SIGNAL_EXTRACTION_PROMPT,
)

from prompts.competitor import (
    COMPETITOR_SEARCH_PROMPT,
    COMPETITOR_EXTRACT_PROMPT,
)

from prompts.poc_eval import (
    POC_EVAL_PROMPT,
)
